# Generated by Django 5.0.4 on 2024-04-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название меню', max_length=100, verbose_name='название')),
                ('url', models.CharField(help_text='Введите ссылку', max_length=200)),
                ('named_url', models.CharField(help_text='Введите именованную ссылку', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menuitem')),
            ],
        ),
    ]
